### ISSUE TITLE
Will your training code contain training using homographies?

### ISSUE THREAD

**Issue by noahzn** [verlab/accelerated_features#10]
Hi, I'm wondering if your training code will contain training using homographies, i.e., given an input image, its corresponding image is generated by homography transformation. Thank you.

**Comment by guipotje** [comment]
Hello @noahzn, thank you for your interest!

Yes, we plan to release the training code using both MegaDepth correspondences and homography warps as described in our paper. Stay tuned for the release!

**Comment by noahzn** [comment]
Hi @guipotje , thanks for your reply! I really look forward to that! Do you have an estimated time for the release?

**Comment by guipotje** [comment]
Hi @noahzn, we plan to release the code in June. Stay tuned!

**Comment by guipotje** [comment]
Hi @noahzn  , code is now available!

**Comment by noahzn** [comment]
@guipotje Hi, thank you! Yes, I cloned it this morning. I think I can only provide the path to coco so that it only uses homographies for training. I will check the code carefully tomorrow. Thank you again!!

**Comment by egbertYeah** [comment]
@noahzn do you test only training in coco, how the performance is ?
