### ISSUE TITLE
When the training code will be released？

### ISSUE THREAD

**Issue by huster-wugj** [verlab/accelerated_features#12]

**Comment by guipotje** [comment]
Hi @huster-wugj, thank you for your interest in our work. We plan to release the code in June. Stay tuned!

**Comment by rshivansh** [comment]
your work is really interesting I want to reproduce training could you please try to upload the training code as soon as you get some time please?

**Comment by guipotje** [comment]
Hello everyone, just letting you know that I'm planning to release the training code until the end of this week!

**Comment by guipotje** [comment]
Training code is now released! Any problems please open a new issue! Thanks for your patience.
