### ISSUE TITLE
How is the warping performed to generate the synthetic training set?

### ISSUE THREAD

**Issue by kilickaya** [verlab/accelerated_features#18]
Hello! 

Thanks for your great work as well as the inference code. Two questions please: 

1) What transformation(s) did you use to generate synthetic warping on MS-COCO images? 
2) Will you release the warping function with the training code release as well? 

Many thanks!

**Comment by guipotje** [comment]
Hi @kilickaya, thank you!

1) We used a custom homography generation scheme, warping the images according to randomly generated parameters.
2) Yes, we will release the full training code! Please subscribe to #12; we will update the status once the code is released. Stay tuned!

**Comment by guipotje** [comment]
Hi @kilickaya, code is now available including training with the homogaraphy generation!
