### ISSUE TITLE
Training XFEAT

### ISSUE THREAD

**Issue by khosrooo** [verlab/accelerated_features#24]
I am very grateful to your comprehensive and organized repository on GitHub.
When do you plan to release the code for training networks for custom applications?"

**Comment by guipotje** [comment]
Thank you for the compliments, @khosrooo!

We should be releasing the training code this month; I'm just finishing up some code cleaning. Please subscribe to issue #12 if you would like to receive a notification.

Best regards.

**Comment by guipotje** [comment]
Hi @khosrooo , code is now available!
