### ISSUE TITLE
can the descriptors of xfeat be input to lightglue for matching?

### ISSUE THREAD

**Issue by noahzn** [verlab/accelerated_features#26]
when I get the descriptors of xfeat points, can i input them to lightglue to train a matcher? would this improve the results?

**Comment by guipotje** [comment]
Hi @noahzn,

Absolutely! XFeat features can be seamlessly 'glued' using [glue-factory](https://github.com/cvg/glue-factory.git).

I’m curious to see how much this will improve the matching. If you train a version, I’d be very interested in learning about the performance outcome!

**Comment by noahzn** [comment]
Yes, I will train one on homography datasets. I'm now waiting for the training code of xfeat.
