### ISSUE TITLE
Requesting a constants.pkl file for pre trained models

### ISSUE THREAD

**Issue by wangy-w** [verlab/accelerated_features#27]
Xfeature has been very helpful to me. Recently, I have been using libtorch to modify it to C++code. During the testing phase, when loading the pre trained model, the following error occurred:
"Terminate called after throwing an instance of 'c10:: Error'"
What(): PytorchStreamReader failed locating file constants.pkl: file not found
”
So I would like to request a constants.pkl file in the pre trained model.Looking forward to your reply

**Comment by guipotje** [comment]
Hi @wangy-w,

Thanks for the interest in our work!

I don't know about this constants.pkl file, it might be a pytorch dependency itself;

I would recommend trying the [ONNX versions](#9 ) or trying to serialize the model with [torch jit](https://pytorch.org/docs/stable/jit.html) and loading in C++.

Best regards.

**Comment by wangy-w** [comment]
@guipotje  Thank you very much for your reply. I have found the answer here https://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html

**Comment by guipotje** [comment]
Nice! Hope it worked for you, just closing the issue. Feel free to open again if issue persists.
