### ISSUE TITLE
Set up multiple GPUs during training

### ISSUE THREAD

**Issue by hbl843449791** [verlab/accelerated_features#30]
hello，I set multiple GPUs as this “--device_num '0,1,2,3,4,5,6,7,8'”，but still only the 0th gpu was used，it seems that the settings are not working。

**Comment by guipotje** [comment]
Hello @hbl843449791, thank you for your interest in our work!

This flag is designed to select a specific GPU from the available ones. The current code does not support multi-GPU usage, but you can easily wrap the original pipeline in a [DistributedDataParallel](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html#distributeddataparallel).

**Comment by hbl843449791** [comment]
> Hello @hbl843449791, thank you for your interest in our work!
> 
> This flag is designed to select a specific GPU from the available ones. The current code does not support multi-GPU usage, but you can easily wrap the original pipeline in a [DistributedDataParallel](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html#distributeddataparallel).

Ok,thank you for your reply.
