### ISSUE TITLE
Training on custom datasets

### ISSUE THREAD

**Issue by hbl843449791** [verlab/accelerated_features#33]
I encountered a problem in the process of creating my own megadepth_indices. I consulted LoFTR instructions and d2-net, but still couldn't find a way to create my own megadepth_indices. Can you provide the code for creating it?

**Comment by guipotje** [comment]
Hello @hbl843449791,

Thank you for your interest in our work!

Could you please provide more details on the issues you're experiencing with the megadepth_indices? Are you saying that you followed the instructions for the indices, but encountered an error?

Best,
Guilherme
