### ISSUE TITLE
using smaller resolution for training

### ISSUE THREAD

**Issue by noahzn** [verlab/accelerated_features#36]
Hi @guipotje 
I want to use 256x256 images for training, the original image size of my dataset is 512x512. During training, the images will be automatically resized to 256x256, right? Could you tell me the correct way to set the parameters? 
What I have done is to set `training_res =256,256`, `grid=(5,5)` in `generateRandomTPS`. But then the keypoint_pos loss is high (about 20), and the reliability is always increasing, and Accuracy/kp_position is always decreasing. This didn't happen when I set `training_res=512,512`. Thank you in advance.

**Comment by guipotje** [comment]
Hi @noahzn,
Yes, this is correct, it should output 256² images with ``training_res = 256``.
I have never tested with such low resolution, is there a reason you need that low res during traning?

**Comment by noahzn** [comment]
Thanks for your response. Because my dataset is 512x512, and I only want to use about 256 points for matching (with LightGlue). When the image is larger, extracting so few numbers of points may not have good result, so I want to downsize the image.
