### ISSUE TITLE
Input is RGB or BGR?

### ISSUE THREAD

**Issue by noahzn** [verlab/accelerated_features#37]
Hi @guipotje  I have another question.
In the training code you use `cv2.imread` to read images. However, the default image read is BGR color mode. Is it a bug?

**Comment by guipotje** [comment]
Hi @noahzn, actually, we use grayscale images, look [here](https://github.com/verlab/accelerated_features/blob/186ea077e55ad0e6a3dfe67bd439be2fc870254b/modules/model.py#L133), we average channels, so it should make little to no difference in using RGB or BGR.
