### ISSUE TITLE
evaluation results

### ISSUE THREAD

**Issue by WJJLBJ** [verlab/accelerated_features#39]
looking forward to your evaluation scripts, thanks!

**Comment by guipotje** [comment]
Hi @WJJLBJ , thank you for the interest in XFeat!
I will release the evaluation scripts soon, sorry for the delay.

**Comment by Zxkai** [comment]
Hi! @guipotje  
I am also looking forward to evaluation scripts and very happy to hear that!
Do you have an estimated time for the release? thanks!

**Comment by Wang86760** [comment]
@guipotje hello，I am looking forward to your evaluation script. Is there a release date now. What do you suggest I refer to when writing my own evaluation script。
