### ISSUE TITLE
Xfeat + LighterGlue (Google Colab)

### ISSUE THREAD

**Issue by adricostas** [verlab/accelerated_features#43]
Hello!

I am using the provided XFeat + LighterGlue Google Colab to test this new model. However, I am not sure Google Colab is loading the correct model. It seems that it is downloading xfeat.pt instead of xfeat-lighterglue.pt
`Downloading: "https://github.com/verlab/accelerated_features/raw/main/weights/xfeat.pt" to /root/.cache/torch/hub/checkpoints/xfeat.pt `

Is this ok? 

Thanks!

**Comment by guipotje** [comment]
Hi @adricostas, this is OK, the LightGlue network is loaded the first time you use the function [match_lighterglue](https://github.com/verlab/accelerated_features/blob/d84a9e2a8615dc7ea408c71cac04c0dd85444a27/modules/xfeat.py#L132).
