### ISSUE TITLE
Features of two similar image by Xfeat.match() didn't match perfectly. 

### ISSUE THREAD

**Issue by AI-Passionner** [verlab/accelerated_features#54]
The key points have significant location shift. I am wondering if there is a bug in the code base. Here is an example, of using XFeat for image alignment.  The Xfeat is fast But it is not as accurate as SIFT and LIghtGlue. 

![xfeat_test](https://github.com/user-attachments/assets/454a631e-dc39-47f9-a19c-914d124a093b)
![image (5)](https://github.com/user-attachments/assets/f9051fd5-bdd1-4837-98ac-2fab701c377e)

**Comment by guipotje** [comment]
Hi @AI-Passionner, thanks for your interest in our work.

This indeed seems strange, because there are too few matches for two visually similar images. The misalignment may be due to the low number of matches. What strategy are you using? Could you share the original images and your code snippet for producing this result?

**Comment by AI-Passionner** [comment]
@guipotje Thans for your quick reply. 
To answer your question, I randomly selected 20 out of >600 features for the debugging purpose. Otherwise, I won't find the problem. This location shift shouldn't happen.

**Comment by AI-Passionner** [comment]
The code snippet:

    # feature extraction
    src_img1 = torch.Tensor(src_img).permute(2, 0, 1)
    dst_img1 = torch.Tensor(dst_img).permute(2, 0, 1)
    mkpts_0, kpts_1 = xfeat.match_xfeat(src_img1, dst_img1, top_k, min_cossim)

    dst_pts = np.array(mkpts_0)
    src_pts = np.array(mkpts_1)

  # image alignment
  h_mat, _ = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)
  aligned = cv2.warpPerspective(src_img, h_mat, dst_img.shape[:2][::-1])

**Comment by AI-Passionner** [comment]
@guipotje Sorry, just found that my code had a bug. I switched the key points accidently. Now it seems solved. thanks.
