### ISSUE TITLE
Eval-MegaDepth-1500

### ISSUE THREAD

**Issue by zw-92** [verlab/accelerated_features#57]
Hello, I evaluated the method on MegaDepth based on the evaluation of LOFTR, but the effect is not good, I can't figure out the problem for the time being. Looking forward to your assessment.

**Comment by guipotje** [comment]
Hello @zw-92, thank you for your interest!

Please notice that we use [poselib](https://github.com/PoseLib/PoseLib)in our paper's evaluation, which provides much better and faster pose estimation than the opencv default implementation used in LoFTR

**Comment by Wang86760** [comment]
@zw-92  你好，可以分享一下您用LOFTR评估方法评估Xfeat的代码吗？谢谢

**Comment by cw314** [comment]
@zw-92 Hello, can you provide  the code for evaluating the Xfeat model?

**Comment by zw-92** [comment]
不好意思，之前有事耽误了。之前因为评估指标非常低，所以暂时将该评估工作放下了。最近因为算力原因，又开始重新研究，等再次核验代码后，会提供评估代码。

**Comment by zw-92** [comment]
> Hello @zw-92, thank you for the interest in our work!
> 
> Please notice that we use [poselib](https://github.com/PoseLib/PoseLib) in our paper's evaluation, which provides much better and faster pose estimation than the opencv default implementation used in LoFTR

**Comment by zw-92** [comment]
> Hello @zw-92, thank you for the interest in our work!
> 
> Please notice that we use [poselib](https://github.com/PoseLib/PoseLib) in our paper's evaluation, which provides much better and faster pose estimation than the opencv default implementation used in LoFTR

Hi, your work is very good, I have reproduced the accuracy of the method in the MegaDepth 1500, and even improved by 1-2 points. I was wondering if I could replace ALike with ROMA if I wanted to optimize XFeat+LightGule.

**Comment by Wang86760** [comment]
@zw-92 你好，可以分享一下怎么使用的poselib吗，我尝试了很多方法都没能实现评估

**Comment by xushangnjlh** [comment]
anyone reproduce the AUC on ScanNet? I have reproduced AUC on MegaDepth1500, but ScanNet AUC is not that high...

**Comment by Odin-byte** [comment]
@xushangnjlh Hey, I am also observing this behavior. Where you able to spot an error in you approach? My scannet evaluation also does not reach the exspected values.
