### ISSUE TITLE
How to improve the success rate of matching the same feature point in multiple consecutive images using xfeat features

### ISSUE THREAD

**Issue by Asherchi** [verlab/accelerated_features#59]
I used xfeat and sift to compare the success rate of matching the feature point in multiple consective images, and the sift is better. then i want to know that how can I get a better results with xfeat?

**Comment by Asherchi** [comment]
the sift results:

**Comment by Asherchi** [comment]
sift results:
![img_matchers_F_800x600](https://github.com/user-attachments/assets/b280a192-d996-4810-8ae3-11e7457fcf60)
xfeat results:
![finalMatchImg_F](https://github.com/user-attachments/assets/ca90ceac-1fb2-4995-b50c-32e5c28d2cd6)

**Comment by issa-ai** [comment]
can you share code ? Also can you share original images so I can test if I get the same results. In my experience you should get better results using Xfeat. I recommend you try Xfeat* if you haven't already.

**Comment by Asherchi** [comment]
xfeat test code is just the author released version, and i used opencv to show 3 images. sift test code is from openMVG. besides, I used xfeat* to test the images, there is no big difference. I can share the images as follow:

**Comment by Asherchi** [comment]
![XAG8df_0132](https://github.com/user-attachments/assets/2252a1ac-40c8-43ac-b108-a200d9ea9708)
![XAG8df_0133](https://github.com/user-attachments/assets/9ae96b0d-7c21-4d2a-8a25-8cbcee7a2e6a)
![XAG8df_0134](https://github.com/user-attachments/assets/67654594-e241-43e3-9476-71c7a375d58e)

**Comment by issa-ai** [comment]
![i1](https://github.com/user-attachments/assets/1be8ea21-f85d-44d3-af46-3f424cb9cbf3)

**Comment by issa-ai** [comment]
The results I showed is from xfeat and has 214 matches. I got +1000 matches from XFeat*.
I suggest you check your code.

**Comment by Asherchi** [comment]
Your result is a matching of two views, while I am doing a matching of three views, matching multiple consecutive frames. Could you please clarify the issue first.

**Comment by Asherchi** [comment]
the results about two views is not bad in my exps. same as yours.
