### ISSUE TITLE
What is the expected input values?

### ISSUE THREAD

**Issue by Parskatt** [verlab/accelerated_features#6]
Here it seems like you expect [0,1]
https://github.com/verlab/accelerated_features/blob/59397446fcc85c777b26ae66a066e8253618cd3c/modules/xfeat.py#L343

But here: https://github.com/verlab/accelerated_features/blob/main/realtime_demo.py it seems you won't normalize from [0,255] -> [0,1] ?

**Comment by Parskatt** [comment]
From some very prelim experiments it seems like [0,255] is the expected range, correct?

**Comment by felipecadar** [comment]
Well, there is an `InstanceNorm2d`  in the base network's forward, so I guess it should work on both. :) 

https://github.com/verlab/accelerated_features/blob/59397446fcc85c777b26ae66a066e8253618cd3c/modules/model.py#L136C8-L136C17

**Comment by Parskatt** [comment]
Haha thats crazy! But params of it are still learnable right? So not completely invariant. But makes sense that I got similar results.

**Comment by felipecadar** [comment]
It's pretty cool, haha. But I don't think the InstanceNorm has any learnable params by default.

**Comment by Parskatt** [comment]
Cool, thanks! My stuff definitely breaks if you use [0,255] haha.

**Comment by Parskatt** [comment]
Ah, and it might be worth mentioning somewhere that your network is invariant to scaling :) (maybe you did in the paper?)

**Comment by felipecadar** [comment]
That's @guipotje making the coolest things, haha.
Thanks for your interest ;)
