### ISSUE TITLE
Corner case when passing images as numpy arrays to detectAndCompute

### ISSUE THREAD

**Issue by tsattler** [verlab/accelerated_features#68]
Thank you very much for the great work!

I noticed a potential issue: Looking at the LighterGlue demo for XFeat, loading an image via imageio seems to be perfectly acceptable. The `imio.v2.imread` function returns a numpy array. Passing it to `detectAndCompute`, the `preprocess_tensor` function converts the numpy array to a tensor. However, this only happens if the image is an RGB image. It crashes if the image is an grayscale image. 
The correspoding code snippet is here: https://github.com/verlab/accelerated_features/blob/main/modules/xfeat.py#L220-L222
Not sure what the most principled solutions is here.

**Comment by guipotje** [comment]
Hi @tsattler, thanks for the feedback!

Indeed there is a bug, thank you for reporting this. I believe with the fix I provided it should work with grayscale (H,W) images. Now I'm checking if numpy array shape is 2 or 3 to handle it correctly, and also some other checks to avoid other shape mismatches.

**Comment by tsattler** [comment]
Looks good, many thanks!
