### ISSUE TITLE
evaluation code

### ISSUE THREAD

**Issue by vegetable233** [verlab/accelerated_features#69]
Your work is very innteresting. When the evaluation code will be released？

**Comment by cw314** [comment]
Yes, this work is perfect. I don't know when the evaluation code of the project will be released. I really need the evaluation code.

**Comment by xtcpete** [comment]
The work is truly inspiring. However, I was unable to reproduce the results reported in the paper. I'm not sure if I'm doing the correct way. Could you please release the evaluation code?

**Comment by guipotje** [comment]
Hello!

Apologies for the delay in releasing the evaluation code. We carefully refactored it to ensure easy usability for everyone.

The evaluation for MegaDepth and ScanNet is now available. Please submit a new request if you have further questions.
