### ISSUE TITLE
OpenVINO support?

### ISSUE THREAD

**Issue by wattanakorn495** [verlab/accelerated_features#8]
I just found OpenVINO does not support InstanceNorm
https://docs.openvino.ai/2023.3/openvino_docs_ops_opset13.html

**Comment by acai66** [comment]
I think it's possible to include InstanceNorm in input preprocessing instead of in the model, or to use an equivalent replacement for InstanceNorm supported by OpenVINO.

**Comment by guipotje** [comment]
Hello @wattanakorn495, as @acai66 mentioned, normalizing the input with standard normalization will have the same effect, thus it can be replaced as described by @acai66. It makes sense to use the same eps=1e-05 as used in the InstanceNorm2D layer.

**Comment by guipotje** [comment]
Closing the issue. If you need further clarification, please feel free to reopen it!
